SHORT_LINK_DOMAIN = "http://localhost"
SHORT_LINK_MIN_LENGTH = 3

USER_FIRST_NAME_MAX_LENGTH = 150
USER_LAST_NAME_MAX_LENGTH = 150

TAG_NAME_MAX_LENGTH = 256
INGREDIENT_NAME_MAX_LENGTH = 256
RECIPE_NAME_MAX_LENGTH = 256
MEASUREMENT_UNIT_MAX_LENGTH = 50

COOKING_TIME_MIN_VALUE = 1
INGREDIENT_AMOUNT_MIN_VALUE = 1
