version: '3.3'
volumes:
  static:
  pg_data:
  media:
services:
  db:
    container_name: foodgram-db
    image: postgres:13
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: foodgram-back
    image: benkendorf/foodgram_backend
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - static:/backend_static
      - media:/app/media

  frontend:
    container_name: foodgram-front
    image: benkendorf/foodgram_frontend
    volumes:
      - static:/app/result_build/build/

  nginx:
    container_name: foodgram-proxy
    image: benkendorf/foodgram_gateway
    depends_on:
      - backend
      - frontend
    ports:
      - "9500:80"
    volumes:
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/staticfiles/
      - media:/media
